blog/urls.py
from django.urls import path
from django.conf.urls import handler404, handler500, handler403


from blog.views import (blog_home,
                        submit_comment,
                        post_detail_view,
                        remove_comment,
                        edit_comment,
                        edit_post,
                        add_post,
                        reaction_add,
                        custom_404,
                        custom_500,
                        custom_403)

urlpatterns = [
    path('', blog_home, name='blog_home'),
    path('comments/submit/<int:post_id>', submit_comment, name='submit_comment'),
    path('detail/<int:post_id>', post_detail_view, name='post_detail'),
    path('add_post/', add_post, name='add_post'),
    path('edit_post/<int:post_id>/', edit_post, name='edit_post'),
    path('comments/delete/<int:comment_id>', remove_comment, name='delete_comment'),
    path('edit_comment/<int:comment_id>/', edit_comment, name='edit_comment'),
    path('reaction/add/<int:post_id>/<reaction_type>', reaction_add, name='add_reaction'),
]


handler404 = custom_404
handler500 = custom_500
handler403 = custom_403

django_settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('blog/', include('blog.urls')),
    path('profile/', include('user_profile.urls')),

    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django_ckeditor_5.fields import CKEditor5Field


class Friendship(models.Model):
    """
    Friendship/followers

    A class representing a friendship between two users.
     It enables one to follow another, and read each others created posts.

    Attributes:
        user (User): The user who initiated the friendship.
        friend (User): The user who is the friend in the friendship.
        created_at (DateTime): The date and time when the friendship was created.

    Methods:
        None

    Usage:
        friendship = Friendship.objects.create(user=user1, friend=user2)
    """
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='user_friendship')

    friend = models.ForeignKey(User, related_name='friendship',
                               on_delete=models.CASCADE, null=True)

    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} friend with {self.friend}"
        # return ', '.join([str(friend) for friend in self.friend.all()])


class Category(models.Model):
    """
    Model class for representing a category.

    Attributes:
        name (str): The name of the category.

    Methods:
        __str__(): Returns a string representation of the category.

    """
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Post(models.Model):
    """
        Post class represents a blog post.

        Attributes:
            title (CharField): The title of the blog post.
            content (TextField): The content of the blog post.
            category (ForeignKey): The category of the blog post.
            created_at (DateTimeField): The date and time of when the blog post was created.
            updated_at (DateTimeField): The date and time of when the blog post was last updated.

        Methods:
            __str__(): Returns a string representation of the blog post.

    """
    author = models.ForeignKey(User, on_delete=models.CASCADE, )
    title = models.CharField(max_length=100)
    content = CKEditor5Field('Text')
    category = models.ManyToManyField(Category, related_name='post_categories')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = 'Post'
        verbose_name_plural = 'Posts'

    def __str__(self):
        return self.title


class Comment(models.Model):
    """

    This class represents a comment made on a post.

    Attributes:
        author (str): The name of the author of the comment.
        content (str): The content of the comment.
        post (Post): The post to which the comment belongs.
        created_at (datetime): The date and time when the comment was created.
        updated_at (datetime): The date and time when the comment was last updated.

    """
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = CKEditor5Field('Add a Comment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Created on: {self.created_at.strftime('%d.%m.%y : %H.%M')} "


class Reactions(models.Model):
    """
    The Reactions class represents a model for storing reactions to posts in a social media application.

    Attributes:
        REACTION_CHOICES (list): List of tuples representing the available reaction choices.
        Each tuple contains a reaction constant and its corresponding display value.

        reaction (CharField): CharField representing the selected reaction.
        It is limited to a maximum length of 10 and can take one of the values defined in REACTION_CHOICES. The default value is 'Like'.

        post (ForeignKey): ForeignKey to the Post model, specifying a one-to-many relationship.
        The reaction is associated with a specific post and will be deleted if the post is deleted.

        user (ForeignKey): ForeignKey to the User model, specifying a one-to-many relationship.
        The reaction is associated with a specific user and will be deleted if the user is deleted.
    """
    LIKE = 'LIKE'
    LOVE = 'LOVE'
    HAHA = 'HAHA'
    WOW = 'WOW'
    SAD = 'SAD'
    ANGRY = 'ANGRY'

    REACTION_CHOICES = [
        (LIKE, 'Like'),
        (LOVE, 'Love'),
        (HAHA, 'Haha'),
        (WOW, 'Wow'),
        (SAD, 'Sad'),
        (ANGRY, 'Angry'),
    ]
    reaction = models.CharField(max_length=10, choices=REACTION_CHOICES,
                                default=LIKE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Reaction'
        verbose_name_plural = 'Reactions'
        unique_together = ['post', 'user']
        ordering = ['-created_at']

    def get_reaction_count(self):
        return Reactions.objects.filter(post=self.post).count()

    def __str__(self):
        return self.reaction

blog/forms.py
from django import forms
from django_ckeditor_5.widgets import CKEditor5Widget
from .models import Comment, Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['category', 'title', 'content', ]
        widgets = {
            'content': CKEditor5Widget(attrs={"class": "django_ckeditor_5"},
                                       config_name="default")
        }


class CommentForm(forms.ModelForm):
    """Form for comments to the article."""
    #
    # def __init__(self, *args, **kwargs):
    #     super().__init__(*args, **kwargs)
    #     self.fields["content"].required = False

    class Meta:
        model = Comment
        exclude = ('author', 'post')
        widgets = {
            "content": CKEditor5Widget(
                attrs={"class": "django_ckeditor_5"},
                config_name="default"

            )
        }

blog/views.py
from datetime import timezone, datetime

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404

from blog.forms import CommentForm, PostForm
from blog.models import Post, Category, Reactions, Comment, Friendship

from django.http import HttpResponseRedirect
from django.urls import reverse

from django.contrib.admin.views.decorators import staff_member_required


def get_post(post_id):
    """
    :param post_id: The ID of the post to retrieve.
    :return: The post object with the specified ID.
    """
    return get_object_or_404(Post, pk=post_id)


def blog_home(request):
    """
    Render the blog home page.

    :param request: The HTTP request object.
    :type request: HttpRequest
    :return: The rendered blog home page.
    :rtype: HttpResponse
    """
    posts = Post.objects.all()
    categories = Category.objects.all()
    comment_form = CommentForm()
    friends_list = []
    if request.user.is_authenticated:
        friends_list = [friend.friend.id for friend in Friendship.objects.filter(user=request.user)]
    reactions_list = Reactions.objects.all()
    context = {
        'posts': posts,
        'categories': categories,
        'comment_form': comment_form,
        'friends_list': friends_list,
        'reactions_list': reactions_list,
    }

    return render(request, 'blog/blog.html', context)


# submit comment
@login_required
def submit_comment(request, post_id):
    """
    :param request: The HTTP request object.
    :param post_id: The ID of the post the comment belongs to.
    :return: A HttpResponseRedirect object if the form is valid and the comment is submitted successfully, else a rendered HTML page with the comment form.

    """
    # Only process form data on POST
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.post = Post.objects.get(pk=post_id)
            comment.save()
            return HttpResponseRedirect(reverse('post_detail',
                                                kwargs={'post_id': post_id}))
    # If not a POST, or the form isn't valid, render the form again with the
    # existing information
    return render(request,
                  'blog/blog.html',
                  {'form': CommentForm()})


def post_detail_view(request, post_id):
    """
    :param request: A HttpRequest object representing the request made by the client
    :param post_id: An integer representing the ID of the post to be viewed
    :return: A rendered HttpResponse object

    This function takes in a request and a post_id and retrieves the post with the given ID using the `get_post` function. It also retrieves the comments for the post using the `Comment.objects.filter` method. The function then creates a context dictionary with the post, comments, and a CommentForm instance. Finally, it renders the 'blog/post_detail.html' template with the context and returns the rendered response.
    """
    post = get_post(post_id)
    comments = Comment.objects.filter(post_id=post.id)
    reactions = Reactions.objects.filter(post_id=post.id)
    context = {
        'post': post,
        'comments': comments,
        'comment_form': CommentForm(),
        'reactions': reactions,

    }

    return render(request, 'blog/post_detail.html', context)


@login_required
@staff_member_required
def remove_comment(request, comment_id):
    """
    Removes a comment.

    :param request: the HTTP request object.
    :type request: ~django.http.HttpRequest
    :param comment_id: the ID of the comment to be removed.
    :type comment_id: int
    :return: an HTTP response redirecting to the post detail page.
    """
    comment = Comment.objects.get(pk=comment_id)
    comment.delete()
    messages.success(request, 'Comment Removed Successfully')

    return HttpResponseRedirect(reverse('post_detail',
                                        kwargs={'post_id': comment.post.id}))


@login_required
@staff_member_required
def remove_category(request, category_id):
    """
    :param request: The request object.
    :param category_id: The ID of the category to be removed.
    :return: The HTTP response redirecting to the 'profile' page.
    """
    category = Category.objects.get(pk=category_id)
    category.delete()
    messages.success(request, 'Category Removed Successfully')

    return HttpResponseRedirect(reverse('profile'))


@login_required
@staff_member_required
def remove_post(request, post_id):
    """
    :param request: The HTTP request object.
    :param post_id: The ID of the post to be removed.
    :return: None
      """
    post = get_post(post_id)
    post.delete()
    messages.success(request, 'Post Removed Successfully')

    return HttpResponseRedirect(reverse('profile'))


@login_required
def add_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.content = request.POST.get('content', '')
            post.updated_at = datetime.now()
            post.save()
        return HttpResponseRedirect(reverse('blog_home'))
    else:
        form = PostForm()
        return render(request, 'blog/add_post.html', {'form': form})


@login_required
@staff_member_required
def edit_post(request, post_id):
    """
    Edit a post.

    :param request: The HTTP request object.
    :param post_id: The ID of the post to be edited.
    :return: If the request method is 'POST', the function updates the content of the post with the value of 'content' from the request's POST data, saves the post, and redirects to the post detail page. Otherwise, it renders the 'blog/edit_post.html' template with the 'post' context variable.

    """
    post = get_post(post_id)
    # form = PostForm(instance=post)
    if request.method == 'POST':
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.author = request.user
            form.updated_at = datetime.now()
            print(form.cleaned_data)
            form.save()
            messages.success(request, 'Post Edited Successfully')
        return HttpResponseRedirect(reverse('post_detail',
                                            kwargs={'post_id': post_id}))
    else:
        form = PostForm(instance=post)
        return render(request,
                      'blog/edit_post.html',
                      {'post': post, 'form': form})


@login_required
@staff_member_required
def edit_comment(request, comment_id):
    """
    Edits a comment.

    :param request: The HTTP request.
    :type request: HttpRequest
    :param comment_id: The ID of the comment to be edited.
    :return: If the request method is POST and the form is valid, the user will be redirected to the 'post_detail' page of the comment's associated post. Otherwise, it will render the 'edit_comment.html' template with the comment form.

    """
    comment = Comment.objects.get(pk=comment_id)

    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('post_detail',
                                                kwargs={'post_id': comment.post.id}))
    else:
        form = CommentForm(instance=comment)

    return render(request,
                  'blog/edit_comment.html',
                  {'form': form})


def reaction_add(request, post_id, reaction_type):
    post = get_post(post_id)
    if not request.user.is_authenticated:
        messages.warning(request,'You are not logged in to add reactions.!')
        return HttpResponseRedirect(reverse('blog_home'))
    if Reactions.objects.filter(post=post, user=request.user).exists():
        existing_reaction = Reactions.objects.get(post=post, user=request.user)
        existing_reaction.reaction_type = reaction_type
        existing_reaction.save()
    else:
        reaction = Reactions.objects.create(post=post, user=request.user,
                                            reaction=reaction_type)
        reaction.save()

    return HttpResponseRedirect(
        reverse('blog_home'))



def custom_404(request, exception):
    return render(request, 'errors/404.html', status=404)


def custom_500(request):
    return render(request, 'errors/500.html', status=500)


def custom_403(request, exception):
    return render(request, 'errors/403.html', status=403)

blog/templates/blog/add_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block extra_title %}| Add Post{% endblock %}

{% block body %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" >
                {% csrf_token %}
                {{ form | crispy }}
                <button class="btn btn-dark" type="submit">Submit</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog.html
{% extends 'base.html' %}
{% block extra_title %}| Blog{% endblock %}

{% block body %}
<main>
    <div class="categories-list">
    {% for category in categories %}
    	<div class="category">
            {{ category }}
        </div>
    {% endfor %}
    </div>

       
        <a class="btn btn-success add-post" href="{% url 'add_post' %}">Add new post</a>
        <div id="caterogies">
            <div>
                <p></p>
            </div>
        </div>
        {% for post in posts %}
            <div class="post">
                <div>
                    <h3>By {{ post.author.username }}

                        {% if user.is_authenticated %}
                            {% if not post.author.username == user.username %}
                                {% if post.author.id in friends_list %}
                                    {#                        can put unfollow link here if needed    #}
                                {% else %}
                                    <a href="{% url 'add_friend' post.author.id %}"><i
                                            class="fa-solid fa-user-plus"></i></a>
                                {% endif %}
                            {% endif %}
                        {% endif %}

                    </h3>
                    <h3><a href="{% url 'post_detail' post.id %}">{{ post.title }}</a></h3>
                    <textarea>{{ post.content | safe }}</textarea>
                    <div class="reactions-comments">


                    </div>
                        <div class="reactions">
                            <div class="reactions-container">
                                <i class="fa-regular fa-heart"></i>
                                <div class="reactions-choices hidden ">
                                    <a href="{% url 'add_reaction' post_id=post.id reaction_type="LIKE" %}"><i
                                            class="fa-regular fa-thumbs-up"></i></a>
                                    <a href="{% url 'add_reaction' post_id=post.id reaction_type="LOVE" %}"><i
                                            class="fa-regular fa-heart"></i></a>
                                    <a href="{% url 'add_reaction' post_id=post.id reaction_type="HAHA" %}"><i
                                            class="fa-regular fa-face-laugh-beam"></i></a>
                                    <a href="{% url 'add_reaction' post_id=post.id reaction_type="WOW" %}"><i
                                            class="fa-regular fa-face-meh-blank"></i></a>
                                    <a href="{% url 'add_reaction' post_id=post.id reaction_type="SAD" %}"><i
                                            class="fa-regular fa-face-frown"></i></a>
                                    <a href="{% url 'add_reaction' post_id=post.id reaction_type="ANGRY" %}"><i
                                            class="fa-regular fa-face-angry"></i></a>
                                </div>
                            {{ post.reactions_set.all.count }}
                        </div>
                        <div class="comments">
                            <a href="{% url 'post_detail' post.id %}"><i class="fa-regular fa-comment"></i>
                            {{ post.comment_set.all.count }}</a>
                        </div>
                    </div>
                </div>
            </div>


        {% empty %}
            <p>No posts yet.</p>
        {% endfor %}

 </main>


    {##}
    <script>
        $(document).ready(function () {
            function showReactionChoices() {
                $(this).find('.reactions-choices').removeClass('hidden');
            }

            function hideReactionChoices() {
                $(this).find('.reactions-choices').addClass('hidden');
            }

            $('.reactions-container').on('mouseover', showReactionChoices);


             $('*').click(function() {
                    $('.reactions-choices').addClass('hidden');
              });
        })

    </script>
{% endblock %}

blog/templates/blog/edit_comment.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block extra_title %}| Edit Comment{% endblock %}

{% block body %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post">
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-dark">Update Comment</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/edit_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block extra_title %}| Edit Post{% endblock %}

{% block body %}

<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <form method="post" action="{% url 'edit_post' post.id %}">
                {% csrf_token %}
                {{ form | crispy }}
                <button type="submit" class="btn btn-dark">Update Post</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% block extra_title %}| Post{% endblock %}

{% block body %}

    <div class="post_detail">
        <h1>{{ post.title }}</h1>
        <p>{{ post.content | safe }}</p>
    {% if post.author == user or user.is_staff %}
        <a href="{% url 'edit_post' post.id %}" class="btn btn-dark" id="edit">Edit Post</a>
    {% endif %}
    

    <form class="center" action="{% url 'submit_comment' post_id=post.id %}" method="post">
        {% csrf_token %}
        {{ comment_form }}
        <button type="submit" class="btn btn-dark" id="submit">Submit</button>
    </form>
    
    <h3 class="post_comments">Comments</h3>
    <ul>
        {% for comment in comments %}
            <li>
                <p class="author">Author: {{ comment.author }}</p>
                <p>{{ comment.content | safe }}</p>
                <span>Created on: {{ comment.created_at }}</span>
                {% if comment.author == user or user.is_staff %}
                    <a href="{% url 'edit_comment' comment.id %}" class="btn btn-success">Edit</a> |
                {% endif %}
                {% if comment.author == user or user.is_staff %}
                    <a href="{% url 'delete_comment' comment.id %}" class="btn btn-danger">Delete</a>
                {% endif %}
            </li>
        {% endfor %}
    </ul>
    </div>
    

{% endblock %}